---
test_name: 1_网络资源-三层网络-添加三层网络-系统网络|l3network_system

includes:
  - !include ../../test_login.yaml
  - !include l3network_queryLayerTwoNetwork.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_l2network_list
  - name: 正常添加三层网络-系统网络
    request:
      url: "{url}/l3network/createL3Network.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        cidr: "10.10.10.0/24"
        closedhcp: false
        endip: ""
        gateway: ""
        iprangeid: ""
        iptype: "1"
        logAction:
          id: 5301
          name: "系统网络-1"
          async: 1
        ltnid: "{l2networkid}"
        ltnname: "{l2networkname}"
        method: "2"
        mtu: 1420
        networktype: "3"
        nid: ""
        operationType: 5301
        pnname: "系统网络-1"
        remark: "系统网络-1"
        shared: false
        startip: ""
        subnetmask: ""
    response:
      status_code: 200
      json:
        code: 1
      #系统网络没有创建vmn资源
      #verify_response_with:
      #  function: verify.verify:check_creat_net_ok
