---
test_name: 3_云资源—云盘-停用云盘|cloudDisk

includes:
  - !include ../test_login.yaml
  - !include query_cloudDisk.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cloudDisk
  - name: 停用或启用云盘
    request:
      url: "{url}/cloudDisk/stop.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{volid}"
        logAction:
          id: 1905
          name: ""
          async: 0
    response:
      status_code: 200
      json:
        code: 1
        id: "{volid}"

---
test_name: 4_云资源—云盘-启用云盘|cloudDisk

includes:
  - !include ../test_login.yaml
  - !include query_cloudDisk.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cloudDisk
  - name: 停用或启用云盘
    request:
      url: "{url}/cloudDisk/start.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{volid}"
        logAction:
          id: 1904
          name: ""
          async: 0
    response:
      status_code: 200
      json:
        code: 1
        id: "{volid}"
