---
test_name: C_云资源—云盘-云盘扩容|cloudDisk


includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: ----
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:choice_no_vm_disk


  - name: ----
    request:
      url: "{url}/cloudDisk/expandVolume.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        volumeid: "{volid}"
        size: "{size}"
        sizeunit: GB
        format: qcow2
        operationType: 1912
        logAction[id]: 1912
        logAction[name]: cloudDisk
        logAction[async]: 1
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDisk_expandVol_ok
        extra_kwargs:
          installpath: "{installpath}"
          size: "{size}"G