---
test_name: 9_云资源—云盘-创建云盘快照|cloudDisk

includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: ----
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:choice_no_vm_disk


  - name: ----
    request:
      url: "{url}/cloudDisk/addSnapshot.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        format: "qcow2"
        logAction:
          id: 1917
          name: ""
          async: 1
        name: "快照1"
        operationType: 1917
        remark: ""
        type: "localFS"
        vmid: null
        volumeid: "{volid}"
        volumetype: 2
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDisk_snapshot_add_ok
