---
test_name: A_云资源—云盘-设置云盘qos|cloudDisk


includes:
  - !include ../test_login.yaml

strict:
  - json:off

marks:
  - parametrize:
      key:
        - rx
        - tx
      vals:
        - [2, 3]
        - [10, 9]
        - [33, 77]

stages:
  - type: ref
    id: login_get_cookie
  - name: ----
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:choice_no_vm_disk
          extra_kwargs:
            flag: 0


  - name: ----
    request:
      url: "{url}/cloudDisk/setQoS.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        bandwidthtype: "2"
        diskbandwidthnum: ""
        diskbandwidthunit: "MB/s"
        logAction:
          id: 1914
          name: "cloudDisk"
          async: 1
        name: "cloudDisk"
        operationType: 1914
        readspeednum: "{rx}"
        readspeedunit: "MB/s"
        targetdev: "vdb"
        vmid: "{vmid}"
        volumeid: "{volid}"
        writespeednum: "{tx}"
        writespeedunit: "MB/s"
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDisk_setQos_ok
        extra_kwargs:
          vmid: "{vmid}"
          rx: "{rx}"
          tx: "{tx}"
