---
test_name: B_云资源—云盘-取消云盘qos|cloudDisk


includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: ----
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:choice_no_vm_disk
          extra_kwargs:
            flag: 0


  - name: ----
    request:
      url: "{url}/cloudDisk/cancleQoS.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        volumeid: "{volid}"
        operationType: 1915
        vmid: "{vmid}"
        device: vdb
        logAction[id]: 1915
        logAction[name]: cloudDisk
        logAction[async]: 1
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDisk_cancleQos_ok
        extra_kwargs:
          vmid: "{vmid}"
