---
test_name: z_云资源—云盘-删除所有云盘|cloudDisk

includes:
  - !include ../test_login.yaml

strict:
  - json:off

marks:
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - name: ---
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:save_all_cloudDisk_list

  - name: 删除所有云盘
    request:
      url: "{url}/cloudDisk/remove.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{ids}"
        logAction:
          id: 1903
          name: "fdfdf"
          async: 1
        operationType: 1903
    response:
      status_code: 200
      json:
        code: 1
        id: "{ids}"
