---
test_name: 5_云资源—云盘-加载|cloudDisk

includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: ---
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:query_use_or_unuse_cloudDisk

  - name: ---
    request:
      url: "{url}/cloudDisk/queryCloudHost.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 5
        limit: 5
        searchitem: 0
        hostid: "{hostid}"
        keyword: null
    response:
      status_code: 200
      save:
        json:
          vmid: rows[0].vmid

  - name: ----
    request:
      url: "{url}/cloudDisk/load.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      data:
        volumeid: "{volumeid}"
        vmid: "{vmid}"
        logAction[id]: 1906
        logAction[name]: "{volname}"
        logAction[async]: 1
        operationType: 1906
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDiskLoad_or_unload_ok
        extra_kwargs:
          vmid: "{vmid}"
          volumeid: "{volumeid}"


