---
test_name: D_云资源—云盘-存储迁移|cloudDisk


includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: 查询一个没有加载到云主机的云盘
    request:
      url: "{url}/cloudDisk/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchitem: 0
        keyword: null
        state: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:choice_no_vm_disk

  - name: 选择物理机
    request:
      url: "{url}/cloudDisk/queryMachines.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        #物理机id
        hostid: "{pmid}"
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          pmid_2: rows[0].hostid
      #verify_response_with:
      #  function: verify.verify:verify_query_cluster_all_phymachine_ok

  - name: 选择物理机上的主存储
    request:
      url: "{url}/cloudDisk/queryMainStorageOfDisk.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        hostid: "{pmid_2}"
        oldhostid: "{pmid}"
        msid: "{msid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          msid_2: rows[0].msid
          msurl: rows[0].url
          msname: rows[0].msname

  - name:
    request:
      url: "{url}/cloudDisk/migrateVM.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        hostid: "{pmid_2}"
        hostip: "{pmip}"
        logAction:
          id: 1913
          name: "hhh"
          async: 1
        msid: "{msid_2}"
        #msname: "main_storage2"
        operationType: 1913
        #pmname: "vm.node1"
        #poolname: "fea151c475db4608b958917c434179aa"
        volumeid: "{volid}"
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_cloudDisk_migrate_ok
        extra_kwargs:
          installpath: "{installpath}"
          pmip: "{pmip}"
          msurl: "{msurl}"
          msname: "{msname}"