---
test_name: 1_云资源—回收站-彻底删除云主机|recycleBin

includes:
  - !include ../test_login.yaml

strict:
  - json:off

marks:
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - name: 查询所有被删除的云主机
    request:
      url: "{url}/recycleCloudHost/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        #这里应传数组，多个id之间用逗号隔开
        order: asc
        offset: 0
        limit: 20
        searchtype: 0
        keyword: null
        state: deleted
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:save_all_deleteVM

  - name: 彻底删除vm
    request:
      url: "{url}/recycleCloudHost/delete.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{ids}"
        logAction:
          id: 1010
          name: "ubuntu19,jjj"
          async: 1
        operationType: 1010
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_delete_all_resource_ok
