---
test_name: 2_vpc—vpc路由器-打开vpc路由器控制台|vpc_router

includes:
  - !include ../../test_login.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/vpc/vpc_router/test_vpcRouter_add.tavern.yaml::1_vpc—vpc路由器-添加vpc路由器|vpc_router"]'

stages:
  - type: ref
    id: login_get_cookie
  - name: 查询vpc路由器列表
    request:
      url: "{url}/vpcrouter/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        keyword: null
    response:
      status_code: 200
      save:
        json:
          routerid: rows[1].routerid
          #routername: rows[1].name

  - name: 打开vpc路由器控制台
    request:
      url: "http://172.16.130.254:15900/vnc_lite.html?path=?token={routerid}"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
    response:
      status_code: 200