---
test_name: 2_云资源—计算规格-修改计算规格|calculationSpecifications

includes:
  - !include ../test_login.yaml
  - !include test_calculationSpecificationsList.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_calculationSpecifications
  - name: --------
    request:
      url: "{url}/calculationSpecifications/update.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        allocatorstrategy: "1"
        bandwidthtype: "1"
        cpunum: "4"
        diskbandwidthnum: "1000"
        diskbandwidthunit: "MB/s"
        logAction:
          id: 1202
          name: "4c8g"
          async: 0
        maxvmcount: ""
        memorynum: "8"
        memoryunit: "G"
        name: "gdfgdfgdfgdgdfgdfgdgdf"
        networkoutbandwidthnum: "10"
        networkoutbandwidthunit: "Mbps"
        networkupbandwidthnum: "1000"
        networkupbandwidthunit: "Kbps"
        remark: ""
        specid: "{calcid}"
        strategymodel: "1"
        volumereadbandwidthnum: ""
        volumereadbandwidthunit: "MB/s"
        volumewritebandwidthnum: ""
        volumewritebandwidthunit: "MB/s"
    response:
      status_code: 200
      json:
        code: 1

