---
test_name: 3_云资源—计算规格-删除计算规格|calculationSpecifications

includes:
  - !include ../test_login.yaml
  - !include test_calculationSpecificationsList.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/calculationSpecifications/test_calculationSpecifications_add.tavern.yaml::1_云资源—计算规格-添加计算规格|calculationSpecifications"]'
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_calculationSpecifications
  - name: --------
    request:
      url: "{url}/calculationSpecifications/remove.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{calcid}"
        logAction:
          id: 1203
          name: "{name}"
          async: 0
    response:
      status_code: 200
      json:
        code: 1
