---
name: 查询云路由镜像列表
description: ----

stages:
  - id: query_cloudRouteImage
    name: ---
    request:
      url: "{url}/vRouterIso/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        keyword: null
    response:
      status_code: 200
      save:
        json:
          mirrorid: rows[0].mirrorid