---
test_name: 2_路由资源—云路由镜像-停用云路由镜像|cloudRouteImage

includes:
  - !include ../../test_login.yaml
  - !include query_cloudRouteImage.yaml

strict:
  - json:off

marks:
  - dependency:["case/routeResources/cloudRouteImage/test_cloudRouteImage_add.tavern.yaml::1_路由资源—云路由镜像-添加云路由镜像|cloudRouteImage"]

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cloudRouteImage
  - name: 停用云路由镜像
    request:
      url: "{url}/vRouterIso/stop.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{mirrorid}"
        logAction:
          id: 2103
          name: "镜像名称"
          async: 0
    response:
      status_code: 200
      json:
        code: 1

---
test_name: 3_路由资源—云路由镜像-启用云路由镜像|cloudRouteImage

includes:
  - !include ../../test_login.yaml
  - !include query_cloudRouteImage.yaml

strict:
  - json:off

marks:
  - dependency:["case/routeResources/cloudRouteImage/test_cloudRouteImage_stop_or_start.tavern.yaml::2_路由资源—云路由镜像-停用云路由镜像|cloudRouteImage"]

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cloudRouteImage
  - name: 停用云路由镜像
    request:
      url: "{url}/vRouterIso/start.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{mirrorid}"
        logAction:
          id: 2102
          name: "镜像名称"
          async: 0
    response:
      status_code: 200
      json:
        code: 1