---
name: 查询二层网络列表|l2network
description: ----

stages:
  - id: query_l2network_list
    name: ---
    request:
      url: "{url}/l2network/queryLayertwonetwork.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        keyword: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:save_l2network_inf