---
test_name: 3_网络资源-二层网络-修改vxlan-pool|vxlan

includes:
  - !include ../../test_login.yaml
  - !include query_vxlan_list.yaml

strict:
  - json:off

marks:
  - parametrize:
      key:
        - remark
        - vxlanpoolname
      vals:
        - [kelian, hellokkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk]
        - [dkkdfdkf, dsjdsjfdfjdfkdjfdfjdfffjdskjfdskfdskfkfjdkfdkfdkfdsfdfk]

  - 'dependency:["case/l2network/vxlan/test_add_vxlanPool.tavern.yaml::1_网络资源-二层网络-添加vxlan-pool|vxlan[1-100-172.16.130.0/24-vxlan-pool-3]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_vxlan_list
  - name: 正常修改vxlan-pool
    request:
      url: "{url}/network/updateVxlan.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        clustername: ""
        endvni: ""
        logAction:
          id: 5002
          async: 1
        remark: "{remark}"
        vnistart: ""
        vtepcidr: ""
        vxlanpoolid: "{vxlanpoolid}"
        vxlanpoolname: "{vxlanpoolname}"

    response:
      status_code: 200
      json:
        code: 1