---
test_name: C_网络资源-二层网络-vxlan-删除vxlan网络|vxlan

includes:
  - !include ../../test_login.yaml
  - !include query_vxlan_list.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/l2network/vxlan/test_add_vxlanNet.tavern.yaml::A_网络资源-二层网络-vxlan-正常vni范围创建vlan网络|vxlan"]'
  - delete
stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_vxlan_list

  - name: 查询vni范围
    request:
      url: "{url}/vin/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          vinid: rows[0].vinid
          vnistart: rows[0].vnistart
          endvni: rows[0].endvni

  - name: 查询vxlan网络
    request:
      url: "{url}/network/selectErVxlan.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          ltnid: rows[0].ltnid
          vni: rows[0].vni

  - name: 查询vxlan网络
    request:
      url: "{url}/network/selcetClusters.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        $ext:
          function: utils.utils:save_vxlan_clusterid_list


  - name: 删除vxlan网络
    request:
      url: "{url}/vxlan/delete.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        id: "{ltnid}"
        logAction:
          id: "5108"
          name: ""
          async: 1
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_delete_vxlan_net_ok
        extra_kwargs:
          vni: "{vni}"
          vxlan_clusterid_list: "{vxlan_clusterid_list}"