---
test_name: 6_网络资源-二层网络-vxlan-添加vni范围|vxlan

includes:
  - !include ../../test_login.yaml
  - !include query_vxlan_list.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/l2network/vxlan/test_add_vxlanPool.tavern.yaml::1_网络资源-二层网络-添加vxlan-pool|vxlan[1-100-172.16.130.0/24-vxlan-pool-3]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_vxlan_list

  - name: 查询vni范围
    request:
      url: "{url}/vin/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          vnistart: rows[0].vnistart
          endvni: rows[0].endvni

  - name: 添加vni范围
    request:
      url: "{url}/vin/addVin.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          id: 5006
          async: 0
        vniname: vni-1
        $ext:
          function: utils.utils:calc_vxlan_vni_range
          extra_kwargs:
            vnistart: "{vnistart}"
            endvni: "{endvni}"
            flag: 1
        vxlanpoolid: "{vxlanpoolid}"
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_add_vxlan_vni_ok
        extra_kwargs:
          flag: 1

---
test_name: 7_网络资源-二层网络-vxlan-添加vni范围|vxlan

includes:
  - !include ../../test_login.yaml
  - !include query_vxlan_list.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/l2network/vxlan/test_add_vxlanPool.tavern.yaml::1_网络资源-二层网络-添加vxlan-pool|vxlan[1-100-172.16.130.0/24-vxlan-pool-3]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_vxlan_list

  - name: 查询vni范围
    request:
      url: "{url}/vin/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          vnistart: rows[0].vnistart
          endvni: rows[0].endvni

  - name: 添加vni范围
    request:
      url: "{url}/vin/addVin.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          id: 5006
          async: 0
        vniname: vni-2
        $ext:
          function: utils.utils:calc_vxlan_vni_range
          extra_kwargs:
            vnistart: "{vnistart}"
            endvni: "{endvni}"
            flag: 2
        vxlanpoolid: "{vxlanpoolid}"
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_add_vxlan_vni_ok
        extra_kwargs:
          flag: 2


---
test_name: 8_网络资源-二层网络-vxlan-添加vni范围|vxlan

includes:
  - !include ../../test_login.yaml
  - !include query_vxlan_list.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/l2network/vxlan/test_add_vxlanPool.tavern.yaml::1_网络资源-二层网络-添加vxlan-pool|vxlan[1-100-172.16.130.0/24-vxlan-pool-3]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_vxlan_list

  - name: 查询vni范围
    request:
      url: "{url}/vin/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        offset: 0
        limit: 5
        vxlanpoolid: "{vxlanpoolid}"
        keyword: null
    response:
      status_code: 200
      json:
        code: 1
      save:
        json:
          vnistart: rows[0].vnistart
          endvni: rows[0].endvni

  - name: 添加vni范围
    request:
      url: "{url}/vin/addVin.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          id: 5006
          async: 0
        vniname: vni-3
        $ext:
          function: utils.utils:calc_vxlan_vni_range
          extra_kwargs:
            vnistart: "{vnistart}"
            endvni: "{endvni}"
            flag: 3
        vxlanpoolid: "{vxlanpoolid}"
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_add_vxlan_vni_ok
        extra_kwargs:
          flag: 3
