---
test_name: 4_硬件设施-集群管理-修改集群名称|cluster

includes:
  - !include ../test_login.yaml
  - !include change_zone.yaml

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cluster
  - name: 验证正常修改集群
    request:
      url: "{url}/cluster/update.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        #这里应传数组，多个id之间用逗号隔开
        cidrnetwork: ""
        clusterid: "{clusterid}"
        clustername: "api-test-after"
        logAction:
          async: 0
          id: 1602
          name: ""
        pmcpumode: "1"
        remark: ""
        vdinetwork: ""
    response:
      status_code: 200
      json:
        code: 1
        msg: null
        id: "{tavern.request_vars.json.clusterid}"
        resourceIds: null
        error: null
        async: 0
