---

test_name: 1_硬件设施-集群管理-添加集群|cluster

includes:
  - !include ../test_login.yaml
  - !include change_zone.yaml

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: logout
  - type: ref
    id: login_get_cookie
  - name: 验证正常添加集群功能
    request:
      url: "{url}/cluster/add.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        cidrnetwork: ""
        cloudcpumode: "None"
        clusterid: null
        clustername: "api-testoooo"
        logAction:
          id: "1601"
          name: "集群名称"
          async: 0
        pmcpumode: "3"
        remark: ""
        vdinetwork: ""
    response:
      status_code: 200
      json:
        code: 1
        msg: null
        id: null
        resourceIds: null
        error: null
        async: 0

  - name: 验证正常添加区域功能, 不带集群名称
    request:
      url: "{url}/cluster/add.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        cidrnetwork: ""
        cloudcpumode: "None"
        clusterid: ""
        clustername: "tttttttttttttttt"
        logAction:
          id: "1601"
          name: ""
          async: 0
        pmcpumode: "1"
        remark: ""
        vdinetwork: ""
    response:
      status_code: 200
      #verify_response_with:
      #  function: verify.verify:check_cluster_add
      json:
        code: 1
        msg: null
        id: null
        resourceIds: null
        error: null
        async: 0