---
test_name: 4_硬件设施-物理机-启用物理机|physicalMachine

includes:
  - !include ../test_login.yaml
  - !include query_physicalmachine.yaml

marks:
  - 'dependency:["case/physicalMachine/test_physical_machine_add.tavern.yaml::1_硬件设施-物理机-添加物理机|physicalMachine[vm.node1-172.16.130.252]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_physicalmachine
  - name: 验证启动物理机
    request:
      url: "{url}/physicalmachine/start.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      data:
        hostid: "{hostid}"
        logAction[id]: 1702
        logAction[name]: "{pmname}"
        logAction[async]: 1

    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_stop_start_pysicalmachine_ok