---
test_name: z_硬件设施-物理机-删除所有物理机|physicalMachine

includes:
  - !include ../test_login.yaml
  - !include query_physicalmachine.yaml

marks:
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_physicalmachine
  - name: 验证正常删除物理机
    request:
      url: "{url}/physicalmachine/remove.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        #这里应传数组，多个id之间用逗号隔开
        ids: "{ids}"
        logAction:
          async: 0
          id: 1706
          name: "{pmname}"
    response:
      status_code: 200
      json:
        code: 1
        msg: null
        id: null
        resourceIds: null
        error: null
        async: 0
