---
test_name: 2_硬件设施-物理机-修改物理机|physicalMachine

includes:
  - !include ../test_login.yaml
  - !include query_physicalmachine.yaml

marks:
  - 'dependency:["case/physicalMachine/test_physical_machine_add.tavern.yaml::1_硬件设施-物理机-添加物理机|physicalMachine[vm.node1-172.16.130.252]"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_physicalmachine
  - name: 验证修改物理机密码
    request:
      url: "{url}/physicalmachine/update.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        hostid: "{hostid}"
        logAction:
          id: 1707
          async: 0
        loginid: root
        loginpw: ""
        remark: "kkkkkkkkkkkk"
        sshport: "22"

    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_physical_update_ok
    delay_after: 1

  - name: 验证停止物理机
    request:
      url: "{url}/physicalmachine/stop.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      data:
        hostid: "{hostid}"
        logAction[id]: 1703
        logAction[name]: "{pmname}"
        logAction[async]: 1

    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_stop_start_pysicalmachine_ok

    delay_after: 5


