---
test_name: Y_云资源—云主机-跟换云主机操作系统|cloudHost

includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: 获取vmid
    request:
      url: "{url}/cloudHost/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchtype: 0
        keyword: null
        state: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:get_stopped_and_qcow2_vm
          extra_kwargs:
            mformat: iso


  - name: 选择非iso并且启用的镜像
    request:
      url: "{url}/cloudHost/queryMirror.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        status: 1
        mtype: 1
        notmformat: iso
        order: asc
        offset: 0
        limit: 5
        keyword: null
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_changeSystem_querySystem_ok
        extra_kwargs:
          vmid: "{vmid}"
      save:
        json:
          mirrorid: rows[0].mirrorid
          template_url: row[0].url


  - name: 跟换操作系统
    request:
      url: "{url}/cloudHost/changeOS.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        vmid: "{vmid}"
        mirrorid: "{mirrorid}"
        operationType: 1023
        logAction[id]: 1023
        logAction[name]: 云主机名称
        logAction[async]: 1
    response:
      status_code: 200
      json:
        code: 1
        id: "{vmid}"
      verify_response_with:
        function: verify.verify:check_changeOs_ok
        extra_kwargs:
          template_url: "{template_url}"
          rootvolumeid: "{rootvolumeid}"
          hostip: "{hostip}"