---
test_name: U_云资源—云主机-创建虚拟光驱|cloudHost

includes:
  - !include ../test_login.yaml

strict:
  - json:off

stages:
  - type: ref
    id: login_get_cookie
  - name: 获取vmid
    request:
      url: "{url}/cloudHost/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchtype: 0
        keyword: null
        state: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:get_console_token
          extra_kwargs:
            state: stopped

  - name: 查询iso镜像
    request:
      url: "{url}/vm/mirror/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        status: 1
        mformat: iso
        order: asc
        offset: 0
        limit: 5
        keyword: null
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_query_cmrom_iso
        extra_kwargs:
          vmid: "{console_token}"
      save:
        $ext:
          function: utils.utils:choice_iso_mirror


  - name: 创建虚拟光驱
    request:
      url: "{url}/cdRom/create.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          id: 1024
          name: ""
          async: 1
        mirrorid: "{mirrorid}"
        vmid: "{console_token}"
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_addCdrom_ok
        extra_kwargs:
          vmid: "{console_token}"
          mirrorid: "{mirrorid}"