---
test_name: z_云资源—云主机-删除所有云主机|cloudHost

includes:
  - !include ../test_login.yaml

strict:
  - json:off

marks:
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - name: ---
    request:
      url: "{url}/cloudHost/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        order: asc
        offset: 0
        limit: 20
        searchtype: 0
        keyword: null
        state: null
    response:
      status_code: 200
      save:
        $ext:
          function: utils.utils:save_cloudHost_list

  - name: 停止所有的云主机
    request:
      url: "{url}/cloudHost/stopVM.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        #console_token也就是vmid
        ids: "{ids}"
        logAction:
          id: 1003
          name: "云主机名称"
          async: 1
        operationType: 1003
    response:
      status_code: 200
      json:
        code: 1
        msg: ""
        id: "{ids}"
        resourceIds: null
        error: null
        async: 1
      verify_response_with:
        function: verify.verify:check_all_vm_stop
        extra_kwargs:
          ids: "{ids}"

  - name: 删除vm
    request:
      url: "{url}/cloudHost/deleteVM.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{ids}"
        logAction:
          id: 1008
          name: "云主机名称"
          async: 1
        operationType: 1008
    response:
      status_code: 200
      json:
        code: 1
        id: "{ids}"
