---
test_name: 1_硬件设施-主存储-添加主存储|main_storage

includes:
  - !include ../test_login.yaml
  - !include ../cluster/change_zone.yaml
  - !include ../zone/query_zone.yaml

marks:
  - 'dependency'
  - parametrize:
      key:
        - msname
        - path
      vals:
        - [1, node1]
        - [2, node2]

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cluster
  - type: ref
    id: query_zone_list
  - name: 正常添加主存储
    request:
      url: "{url}/primarystorage/add.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        clusterId: "{clusterid}"
        clustername: "{clustername}"
        id: ""
        logAction:
          id: 1801
          name: "{msname}"
          async: 1
        name: "{msname}"
        opt: ""
        remark: ""
        type: "1"
        url: "/mnt/localfs/{path}"
        zoneName: "{zoneName}"
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_mainStorage_addCluster_ok
        extra_kwargs:
          clusterId: "{clusterid}"
          uri: "/mnt/localfs/{path}"

