---
test_name: 3_硬件设施-主存储-停用主存储|main_storage

strict:
  - json:off

includes:
  - !include ../test_login.yaml
  - !include mainStorage_query.yaml

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_mainStorage
  - name: ----
    request:
      url: "{url}/primarystorage/stop.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          async: 1
          id: 1803
          name: ""
        ids: "{msid}"
    response:
      status_code: 200
      json:
        id: "{msid}"

  - name: ----
    delay_before: 1
    request:
      url: "{url}/primarystorage/start.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        logAction:
          async: 1
          id: 1804
          name: ""
        ids: "{msid}"
    response:
      status_code: 200
      json:
        id: "{msid}"

