---
test_name: z_硬件设施-主存储-删除所有主存储|main_storage

includes:
  - !include ../test_login.yaml

strict:
  - json:off

marks:
  - delete
  #- "dependency:1_硬件设施-主存储-添加主存储|main_storage"

stages:
  - type: ref
    id: login_get_cookie
  - name: 验证查询主存储列表
    request:
      url: "{url}/primarystorage/query.do"
      method: GET
      verify: false
      headers:
        Cookie: "{cookie}"
      params:
        keyword: ""
        limit: 20
        offset: 0
        order: asc
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_mainStorage_query_ok
      save:
        json:
          msid: rows[0].msid
          msname: rows[0].msname
        $ext:
          function: utils.utils:save_mainStorage_msids
          extra_kwargs:
              all: 0

  - name: 验证删除主存储
    request:
      url: "{url}/primarystorage/delete.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        clusterId: "空字段"
        id: "{msids}"
        logAction:
          async: 1
          id: 1803
          name: ""
    response:
      status_code: 200
      json:
        async: 1
        code: 1
        error: null
        id: "{msids}"
        msg: null
        resourceIds: null
        verify_response_with:
          function: verify.verify:check_delete_mainStorage_ok
          extra_kwargs:
            ids: "{msids}"


