---
test_name: 3_网络资源-二层网络-删除二层网络|l2net

includes:
  - !include ../../test_login.yaml
  - !include query_l2network.yaml

strict:
  - json:off

marks:
  - usefixtures:
      - calc_l2vmn_number

  - 'dependency:["case/l2network/l2net/test_l2network_add.tavern.yaml::1_网络资源-二层网络-添加二层网络|l2net"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_l2network_list
  - name: 正常删除二层网络
    request:
      url: "{url}/l2network/remove.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        id: "{l2networkid}"
        logAction:
          id: "5103"
          name: ""
          async: 1
    response:
      status_code: 200
      json:
        code: 1
      verify_response_with:
        function: verify.verify:check_delete_net
        extra_kwargs:
          l2vmn_num: "{calc_l2vmn_number}"