---
test_name: 3_硬件设施-镜像服务器-启用镜像服务器|mirrorServer

includes:
  - !include ../test_login.yaml
  - !include mirrorServer_query.yaml

strict:
  - json:off

marks:
  - 'dependency:["case/mirrorServer/test_mirrorServer_add.tavern.yaml::1_硬件设施-镜像服务器-添加镜像服务器|mirrorServer"]'

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_mirrorServerList
  - name: 停用镜像服务器
    request:
      url: "{url}/mirrorserver/enable.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        id: "{mirrorServerId}"
    response:
      status_code: 200
      json:
        code: 1