---
test_name: 3_硬件设施-区域管理-修改区域名称

includes:
  - !include ../test_login.yaml
  - !include query_zone.yaml

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_zone_list
  - name: 验证正常修改区域
    request:
      url: "{url}/zone/update.do"
      method: POST
      verify: false
      headers:
        Content-Type: application/json;charset=UTF-8
        Cookie: "{cookie}"
      json:
        #这里应传数组，多个id之间用逗号隔开
        domainid: "{ids}"
        domainname: "update后的名字"
        logAction:
          id: "1502"
          name: ""
          async: 0
    response:
      status_code: 200
      json:
        code: 1
        msg: null
        id: "{tavern.request_vars.json.domainid}"
        resourceIds: null
        error: null
        async: 0
