---
test_name: 1_硬件设施-主存储-添加主存储

includes:
  - !include ../test_login.yaml
  - !include ../b_cluster/change_zone.yaml
  - !include ../a_zone/query_zone.yaml

marks:
  - parametrize:
      key:
        - msname
        - path
      vals:
        - [main_storage1, node1]
        - [main_storage2, node2]

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cluster
  - type: ref
    id: query_zone_list
  - name: 正常添加集群
    request:
      url: "{url}/primarystorage/add.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        clusterId: "{clusterid}"
        clustername: "{clustername}"
        id: ""
        logAction:
          id: 1801
          name: "{msname}"
          async: 1
        name: "{msname}"
        opt: ""
        remark: ""
        type: "1"
        url: "/mnt/localfs/{path}"
        zoneName: "{zoneName}"
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_mainStorage_addCluster_ok

    delay_after: 10
