---
test_name: z_云资源-云盘规格-删除全部云盘规格|cloudDiskSpec

includes:
  - !include ../test_login.yaml
  - !include test_cloudDiskSpec_query.yaml

marks:
  - delete

stages:
  - type: ref
    id: login_get_cookie
  - type: ref
    id: query_cloudDiskSpec
  - name: 验证正常删除云盘规则
    request:
      url: "{url}/cloudDiskSpec/delete.do"
      method: POST
      verify: false
      headers:
        Cookie: "{cookie}"
      json:
        ids: "{ids}"
        logAction:
          id: 1103
          name: "云盘规格名称"
          async: 0
    response:
      status_code: 200
      json:
        code: 1
        msg: null
        id: "{tavern.request_vars.json.ids}"
        resourceIds: null
        error: null
        async: 0
