---
test_name: 验证角色管理

includes:
  - !include test_login.yaml

stages:
  - type: ref
    id: login_get_cookie
  - name: 验证正常添加功能
    request:
      url: "{url}/role/add.do"
      method: POST
      verify: false
      headers:
        Content-Type: application/json;charset=UTF-8
        Cookie: "{cookie}"
      json:
        roleId: "apitest"
        name: "apu"
        sortNum: "0"
        status: "1"
        logAction:
          id: "6021"
          name: "apu"
          async: 0

    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_add_role


  - name: 验证正常删除角色功能
    request:
      url: "{url}/role/remove.do"
      method: POST
      verify: false
      headers:
        Content-Type: application/json;charset=UTF-8
        Cookie: "{cookie}"
      json:
        #这里应传数组，多个id之间用逗号隔开
        ids: "apitest"
        logAction:
          id: "6023"
          name: "apu"
          async: 0

    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_remove_role


