---
test_name: py machine stop or start

includes:
  - !include common.yaml
  - !include test_login.tavern.yaml

stages:
  - name: check stop py_machine
    request:
      url: "{url}/physicalmachine/stop.do"
      method: POST
      verify: false
      headers:
        Cookie: "my_id={userId}; LOCALE=zh_CN;{cookie}"
      data:
        hostid: e6ce162605524326bdff5beb7f026759
        ogAction[id]: 1703
        logAction[name]: vm.compute
        logAction[async]: 0
    response:
      status_code: 200
      verify_response_with:
        function: verify.verify:check_stop_py_machine